name: Deploy odoc

on:
  push:
    branches:
      - master

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: sudo apt-get install -y libgdbm-compat-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml 4.12.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
          opam-pin: false
          opam-depext: false
          dune-cache: true

      - name: Install libgdbm-dev
        run: sudo apt-get install libgdbm-dev

      - name: Deploy odoc to GitHub Pages
        uses: ocaml/setup-ocaml/deploy-doc@v2
